### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by menesakdeniz** [PerfectLaugh/RejectLobbyDisabler#1]
This extension cause server crash, can you fix this?
you can look crashes in this url :
https://crash.limetech.org/stats/5a47496fe5b9fa91fbd5ae413e244f91af6c24e10febd8136223aa15836946a3f632692f

is there any way to debug the extension to locate where it crash?

**Comment by PerfectLaugh** [comment]
This is not my extension.
RejectLobbyDisabler takes differnet approach from LobbySessionFixer.
